---
- name: Start Minikube
  command: minikube start --driver=docker
  become: no
  become_user: "{{ ansible_user }}"
  environment:
    MINIKUBE_HOME: "/home/{{ ansible_user }}"
    CHANGE_MINIKUBE_NONE_USER: "true"



