---
- name: Add Minikube GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Add Minikube APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
- name: Install Minikube and Kubectl
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - minikube
    - kubectl