apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "easy-school.namespace" .  }}
  name: easy-school-app-secret
  labels:
    {{- include "easy-school.labels" . | nindent 4}}
type: Opaque
stringData:
  DB_USERNAME: "easy-school-user"
  DB_PASSWORD: "Gi6J6WPGnjQpuuzUbv47"