apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ include "easy-school.namespace" .  }}
  name: easy-school-app-config
  labels:
    {{- include "easy-school.labels" . | nindent 4}}
data:
  DB_DATABASE: easy_school
  DB_HOST: easy-school-database-svc
  DB_PORT: "5432"
