app:
  replicas: 2
  env: staging
  container:
    image: uthutu/easy-school
    tag: beta-1
    name: easy-school
  ports:
    containerPort: 8000
    protocol: TCP
  service:
      name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 30007

hpa:
  enabled: false



database:
  pvc:
    storage: 3Gi
  service:
    protocol: TCP
    port: 5432
    targetPort: 5432
  containers:
    name: db
    image: postgres:15
    containerPort: 5432
  resources:
    cpu: 300m
    memory: 256Mi
