---
- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install kubernetes package
  pip:
    name: kubernetes
    state: present

- name: Create namespace
  vars:
    namespace_prefix: "two-tier"
  k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace_prefix }}-{{ env }}"
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"