apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ include "easy-school.namespace" .  }}
  name: easy-school-database-pvc
  labels:
        {{- include "easy-school.labels" . | nindent 4}}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.pvc.storage }}