apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "easy-school.namespace" .  }}
  name: easy-school-database-secret
  labels:
    {{- include "easy-school.labels" . | nindent 4}}
type: Opaque
stringData:
  username: "easy-school-user"
  password: "Gi6J6WPGnjQpuuzUbv47"