apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "easy-school.namespace" .  }}
  name: easy-school-database-svc
  labels:
    {{- include "easy-school.labels" . | nindent 4}}
spec:
  selector:
    {{- include "easy-school.labels" . | nindent 4}}
  ports:
    - protocol: {{ .Values.database.service.protocol }}
      port: {{ .Values.database.service.port }}
      targetPort: {{ .Values.database.service.targetPort }}
  type: ClusterIP