# Generated by Django 5.0.3 on 2024-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cnic',
            field=models.CharField(default='', max_length=30),
        ),
    ]
