name: "Update helm tag"
description: "Updating helm tag"

inputs:
  environment:
    type: string
    description: ""
    required: true

runs:
  using: "composite"


  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: '${{ github.token }}'

    - name: Update tag in Helm chart
      shell: bash
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/easy-school-chart/values-${{ inputs.environment }}.yaml

    - name: Commit and push changes
      shell: bash
      run: |
        git branch
        git config --global user.email "uthmanayinde6@gmail.com"
        git config --global user.name "uuthman"
        git add helm/easy-school-chart/values-${{ inputs.environment }}.yaml
        git commit -m "Update tag in Helm chart"
        git push