---
- name: Add Helm repo for Prometheus
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: 'https://prometheus-community.github.io/helm-charts'
- name: Add Helm repo for Grafana
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: 'https://grafana.github.io/helm-charts'
- name: Update Helm repos
  command: helm repo update
- name: Install Prometheus using Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: monitoring
    create_namespace: 'yes'
  environment:
    KUBECONFIG: '/home/{{ ansible_user }}/.kube/config'
- name: Install Grafana using Helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring
    create_namespace: 'yes'
    values:
      adminPassword: "admin"
      service:
        type: NodePort
  environment:
    KUBECONFIG: '/home/{{ ansible_user }}/.kube/config'
#- name: Wait for Prometheus Pods to be Running
#  command: >
#    kubectl rollout status deployment/prometheus-server
#    -n monitoring
#    --timeout=300s
#  register: prometheus_rollout
#  failed_when: prometheus_rollout.rc != 0
#  changed_when: false
#
#  retries: 10
#  delay: 30
#- name: Wait for Grafana Pods to be Running
#  command: >
#    kubectl rollout status deployment/grafana
#            -n monitoring
#            --timeout=300s
#  register: grafana_rollout
#  failed_when: grafana_rollout.rc != 0
#  changed_when: false
#
#- name: Get Grafana Admin Password
#  kubernetes.core.k8s_info:
#    kind: Secret
#    name: grafana
#    namespace: monitoring
#  register: grafana_secret
#
#- name: Print Grafana Admin Password
#  debug:
#    msg: >-
#      Grafana Admin Password: {{
#      grafana_secret.resources[0].data['admin-password'] | b64decode }}

