---
- name: Setup Development Environment
  hosts: dev
  become: yes
  roles:
    - docker
    - minikube
    - helm

- name: Setup Development Environment
  hosts: staging
  become: yes
  roles:
    - docker
    - minikube
    - helm

- name: Setup Production Environment
  hosts: prod
  become: yes
  roles:
    - docker
    - minikube
    - helm