---
- name: Setup Development Environment
  hosts: dev
  become: yes
  roles:
    - docker
    - role: andrewrothstein.kubectl
    - role: gantsign.minikube
    - minikube
    - helm
    - prometheus_grafana
    - create_namespace
    - argocd
