name: "This push in to docker"
description: "Allows us to push to docker"

inputs:
  username:
    type: string
    required: true


runs:
  using: "composite"


  steps:
    - name: Validate Username
      shell: bash
      run: |
          if [[ -z "${{ inputs.username }}" ]]; then
            echo "Error: username input is required."
            exit 1
          fi
    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ inputs.username }}/easy-school:${{github.run_id}}"