default_region = "us-east-1"
vpc_cidr = "20.0.0.0/16"
infra_env = "app-prod-tf"
project_name = "easy-school"
subnet_cidr_block = "20.0.0.0/24"
subnet_availability_zone = "us-east-1b"
instance_size = "t2.micro"
