name: Deploy Staging environment

concurrency:
  group: deploy-${{ vars.ENVIRONMENT }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    paths:
      - terraform/environment/staging/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy-to-dev:
    environment: staging
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: 'Setup: AWS Login and Terraform init'
        uses: ./.github/actions/terraform-init
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: ${{ vars.TF_AWS_ROLE }}

      - name: 'Test: check and validate'
        uses: ./.github/actions/terraform-test
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: ${{ vars.TF_AWS_ROLE }}

      - name: 'Deploy: to ${{ vars.ENVIRONMENT }}'
        uses: ./.github/actions/terraform-apply
        with:
          environment: ${{ vars.ENVIRONMENT }}
          region: ${{ vars.AWS_REGION }}
          iam-role: ${{ vars.TF_AWS_ROLE }}

#      - name: "Update ip on Ansible ${{ vars.ENVIRONMENT }} inventory"
#        uses: ./.github/actions/ansible-update-ip
#        with:
#          environment: ${{ vars.ENVIRONMENT }}